import type { Metadata } from "next";
import "../theme/globals.css";
import React from 'react'
import { Box, Text, Image, Flex, Heading, VStack, } from '@chakra-ui/react'
import { FaFacebookF, FaPhoneAlt } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";
// import { IoLogoInstagram, } from "react-icons/io5";
import RootWrapper from "@/RootWrapper";
import Link from "next/link";
// import { RiFacebookFill } from "react-icons/ri";
import { BsFillTelephoneFill } from "react-icons/bs";
// import { MdEmail } from "react-icons/md";
import { ImLocation } from "react-icons/im";
import { GrMail } from "react-icons/gr";
import { RiFacebookFill } from "react-icons/ri";
import { IoLogoInstagram } from "react-icons/io";
import { CONTACT_DETAILS, PAGES, QUICK_LINKS, SOCIAL_LINKS } from "@/app-config";
import { IoMail } from "react-icons/io5";

const logopath = '/assets/home/favicon.ico'
export const metadata: Metadata = {
  title: "KangarooCare-AI",
  description: "Generated by create next app",
  icons: [logopath],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Flex direction='column' h='100vh' w='100%' as='body'>
        <RootWrapper>
          <Header />
          <Box flex="1 0 auto">
            {children}
          </Box>
          <Footer />
        </RootWrapper>
      </Flex>
    </html>
  );
}


function Header() {
  return (
    <Box>

      <Flex p="2" bgColor='app.primary' justify='space-between'>
        <Flex align='center' color='app.white' gap='20px' mt='2px'>
          <Link href={SOCIAL_LINKS.Facebook} target="_blank" ><FaFacebookF size='20' /></Link>
          <Link href={SOCIAL_LINKS.Instagram} target="_blank" ><FaInstagram size='20' /></Link>
          <Link href={SOCIAL_LINKS.LinkedIn} target="_blank" ><FaLinkedinIn size='20' /></Link>
        </Flex>
        <Flex color='app.white' gap='3' align="center" >
          <Flex align="center" gap='2'>
            <FaPhoneAlt size='19' />
            <Text >{CONTACT_DETAILS.Phone}</Text>
          </Flex>
          <Box h='5' borderLeft='2px' borderColor='app.white' borderStyle='dashed' />
          <Flex align="center" gap='2'>
            <IoMail size='22' />
            <Text  >{CONTACT_DETAILS.Email}</Text>
          </Flex>
        </Flex>
      </Flex>

      <Flex position='absolute' w='full' p='3' justify='space-between' fontFamily='jua'>
        <Flex align='center' gap='2'>
          <Link href={PAGES.Home.path}><Image src="/assets/home/favicon.ico" alt="logo" width="65px" /></Link>
          <Heading fontSize='3xl' color='app.primary' >Kangaroo Care AI</Heading>
        </Flex>
        <Flex align='center' gap='5' >
          {QUICK_LINKS.map((link, idx) => {
            return <Text key={idx} fontSize='xl' color='app.primary' ><Link href={link.path}>{link.title}</Link></Text>
          })}
        </Flex>
      </Flex>
    </Box>
  )
}

function Footer() {
  return (
    <Box bgColor='app.grey1' >
      <Flex aria-label="footer-top" maxW='1280px' mx='auto' p="10px" gap='5'  >

        <Box flex='2'>
          <Image src='/assets/home/logo-2.png' alt="logo-2" maxW="300px" mb='10px' />
          <br />
          <VStack spacing='5' align='start' >
            <Flex gap='10px' >
              <ImLocation size="28" />
              <Text >{CONTACT_DETAILS.Address}</Text>
            </Flex>
            <Flex gap='10px'>
              <BsFillTelephoneFill size='25' />
              <Text >{CONTACT_DETAILS.Phone}</Text>
            </Flex>
            <Flex gap='10px'>
              <GrMail size='25' />
              <Text >{CONTACT_DETAILS.Email}</Text>
            </Flex>
          </VStack>
        </Box>

        <Box flex='1'>
          <Heading fontSize='3xl' color="app.primary" mb='4' >Quick Links</Heading>
          <Box display="flex" flexDirection="column" gap="2">
            {QUICK_LINKS.map((link, idx) => {
              return <Text key={idx} ><Link href={link.path}>{link.title}</Link></Text>
            })}
          </Box>
        </Box>

        <Box flex='2'>
          <Heading color="app.primary" fontSize='3xl'>Our Mission</Heading>
          <Text mb='5'>
            At Kangaroo Care AI, our mission is to revolutionize neonatal care with AI-powered incubators that prioritize warmth, safety, and bonding. We combine advanced technology with compassionate design to support healthcare professionals and families, ensuring optimal outcomes for infants in their most critical early moments.
          </Text>
          <Flex justify='start' color='app.grey3' gap='16px' >
            <Link href={SOCIAL_LINKS.Facebook}><RiFacebookFill size="25px" /></Link>
            <Link href={SOCIAL_LINKS.Instagram}><IoLogoInstagram size="25px" /></Link>
            <Link href={SOCIAL_LINKS.LinkedIn}><FaLinkedinIn size="25px" /></Link>
          </Flex>
        </Box>
      </Flex>

      < Flex aria-label="footer-bottom" p='4px' justify='space-between' bgColor='app.grey3' >
        <Text color='app.white'>Copyright &copy; {new Date().getFullYear()} kangaroocareai.com All Rights Reserved</Text>
        <Flex align='center' gap='2'>
          <Text color="app.white" >Powered By :</Text>
          <Link href='https:www.syntaxfit.com'><Image src="/assets/home/syntaxfit.png" alt="company_logo" /></Link>
        </Flex>
      </ Flex>
    </Box >
  )
}

