import type { Metadata } from "next";


import "../theme/globals.css";
import { ChakraProvider } from "@chakra-ui/react";



import React from 'react'
import { Box, Text, Image } from '@chakra-ui/react'
import { FaFacebookF } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";
import { FiPhone } from "react-icons/fi";
import { IoMailOutline } from "react-icons/io5";


const logopath = '/assets/favicon.co'
export const metadata: Metadata = {
  title: "Kangroo-Care-ai",
  description: "Generated by create next app",
  icons: [logopath],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ChakraProvider> {children}</ChakraProvider>
        <Footer />
      </body>
    </html>
  );
}


function Header() {
  return (
    <Box padding="10" rounded="sm" backgroundColor='#286AA3'>
      <Box display='flex' gap='30'>
        <FaFacebookF color='#FBEFDD' />
        <FaInstagram color='#FBEFDD' />
        <FaLinkedinIn color='#FBEFDD' />
        <Box display="flex" gap='5' alignItems="center" ml="auto" >
          <FiPhone color='#FBEFDD' />
          <Text color="#FBEFDD">+923322842727</Text>
          <IoMailOutline color="#FBEFDD" />
          <Text color="#FBEFDD" >mohammadlaeeq91@gmail.com</Text>
        </Box>
      </Box>
    </Box>

  )
}

function Footer() {
  return (
    <Box padding='6' rounded='sm' backgroundColor='#444343' mt='527'>
      <Box display='flex' gap='30'>
        <Text color='#FBEFDD' >Copyright &copy; {new Date().getFullYear()} kangaroocareai.com All Rights Reserved</Text>
        {/* <Box display="flex" gap='5' ml="auto" >
          <Text color="#FBEFDD" >Powered By : <Image src="/syntaxfit.png" alt="company_logo"></Image></Text>
        </Box> */}
        <Box display="flex" alignItems="center" gap={2} ml="auto">
          <Text color="#FBEFDD">Powered By :</Text>
          <Image src="/syntaxfit.png" alt="company_logo" boxSize="100px" width='20' height='20' />
        </Box>
      </Box>

    </Box>

  )
}

