import type { Metadata } from "next";
import "../theme/globals.css";
import React from 'react'
import { Box, Text, Image } from '@chakra-ui/react'
import { FaFacebookF } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";
import { FiPhone } from "react-icons/fi";
import { IoMailOutline } from "react-icons/io5";
import RootWrapper from "@/RootWrapper";


const logopath = '/assets/favicon.co'
export const metadata: Metadata = {
  title: "Kangroo-Care-ai",
  description: "Generated by create next app",
  icons: [logopath],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Box as='body'>
        <RootWrapper>
          <Header />
          {children}
          <Footer />
        </RootWrapper>
      </Box>
    </html>
  );
}


function Header() {
  return (
    <Box padding="7px" rounded="sm" backgroundColor='#286AA3'>
      <Box display='flex' gap='20px' mt='2px'>
        <FaFacebookF color='#FBEFDD' />
        <FaInstagram color='#FBEFDD' />
        <FaLinkedinIn color='#FBEFDD' />
        <Box display="flex" gap='5' alignItems="center" ml="auto" >
          <FiPhone color='#FBEFDD' />
          <Text color="#FBEFDD">+923322842727</Text>
          <IoMailOutline color="#FBEFDD" />
          <Text color="#FBEFDD" >mohammadlaeeq91@gmail.com</Text>
        </Box>
      </Box>
    </Box>

  )
}

function Footer() {
  return (
    <Box padding='2px' rounded='sm' backgroundColor='#444343'>
      <Box display='flex' gap='30'>
        <Text color='#FBEFDD' >Copyright &copy; {new Date().getFullYear()} kangaroocareai.com All Rights Reserved</Text>
        <Box display="flex" alignItems="center" gap={2} ml="auto">
          <Text color="#FBEFDD">Powered By :</Text>
          <a href="https://syntaxfit.com/"><Image src="/syntaxfit.png" alt="company_logo" /></a>
        </Box>
      </Box>

    </Box>

  )
}

